// Русские строки ИИ-разбора (срез U6a): происхождение совета, состояния задания, ошибки и подсказки.
// Сырые коды сервера всегда показываются рядом; неизвестный код не ломает панель.

export const ADVICE_LABELS = {
  intro: 'Совет создаёт языковая модель по данным этого анализа. Рекомендации могут содержать ошибки; гипотезы требуют проверки. Вердикт SLA не меняется.',
  provenanceTitle: 'Происхождение совета',
  model: 'Модель',
  promptVersion: 'Версия prompt',
  requests: 'Запросов к модели',
  requestsRetry: 'первый запрос и один повтор при ошибке схемы ответа (ADR 0021)',
  duration: 'Время ответа',
  runner: 'Исполнитель',
  invocation: 'Идентификатор вызова',
  notStated: 'не указана',
  promptLegacy: (version: string): string => `${version} (прежняя версия)`,
  durationText: (milliseconds: number): string => `${(milliseconds / 1000).toFixed(1).replace('.', ',')} с`,
  evidence: {
    rule: 'Правило',
    metrics: 'Метрики',
    overall: 'Метрики всего прогона',
    open: 'Открыть в таблицах',
    openFor: (label: string): string => `Открыть в таблицах: ${label}`,
    types: {
      metric_summary: 'Сводка метрик',
      policy_check: 'Проверка правила',
      diagnostic: 'Диагностика',
      resource_summary: 'Сводка ресурсов',
      window_policy_summary: 'Сводка правил по окнам',
      resource_policy_check: 'Проверка ресурсного правила',
      resource_binding: 'Привязка ресурсного ряда',
      diagnostic_summary: 'Сводка диагностики',
      correlation_pair: 'Корреляция ресурса и нагрузки',
      anomaly_check: 'Проверка аномалии',
      window_metric_summary: 'Сводка метрик окна',
      source_summary: 'Сводка источников',
      opensearch_errors: 'Ошибки из OpenSearch',
      postgres_context: 'Контекст PostgreSQL',
      trend_check: 'Проверка тренда',
      trend_summary: 'Сводка трендов',
    } as Record<string, string>,
  },
  // Выбор модели (срез CM5 ADR 0023). Подписи назначения (endpoint) нет: решение владельца 2026-10-06.
  modelChoice: {
    label: 'Модель',
    measured: 'модель измерена',
    notMeasured: 'не измерена',
    unmeasuredNote: 'Модель не входила в эксперимент ADR 0021: качество советов не проверено.',
    once: 'Совет создаётся один раз на анализ: модель уже выбрана и показана в происхождении совета.',
    jobModel: 'Модель задания',
  },
  codeLabel: 'код',
  hintLabel: 'Что делать',
  stateUnknown: 'Неизвестное состояние',
  unknownFailure: 'Совет не получен: причина не опознана этой версией интерфейса.',
  unknownUnavailable: 'ИИ-разбор недоступен: причина не опознана этой версией интерфейса.',
  unknownFailureHint: 'Повторите запрос позже; если ошибка остаётся, сообщите администратору код ошибки.',
  apiBusy: 'Сервер сейчас не принимает ИИ-разбор: он занят заданием или это задание уже выполняется.',
  apiBusyHint: 'Дождитесь завершения текущего задания и запросите совет ещё раз.',
  apiUnavailable: 'ИИ-разбор не настроен на сервере.',
  apiUnavailableHint: 'Администратору: настройте ИИ-runner по docs/user/advisory-ai.md. Анализ и вердикт SLA от этого не зависят.',
  states: {
    QUEUED: 'В очереди',
    PROCESSING: 'Выполняется',
    COMPLETE: 'Готово',
    FAILED: 'Ошибка',
    UNAVAILABLE: 'Недоступно',
    CANCELLED: 'Отменено',
  } as Record<string, string>,
  failure: {
    INPUT_LIMIT: 'Данные анализа слишком велики для ИИ-разбора.',
    OUTPUT_LIMIT: 'Ответ модели превысил допустимый размер.',
    INVALID_ANALYSIS: 'Результат анализа не прошёл проверку перед отправкой в модель.',
    INVALID_OUTPUT: 'Ответ модели не соответствует контракту совета.',
    UNKNOWN_EVIDENCE_REFERENCE: 'Модель сослалась на evidence, которого нет в анализе.',
    TIMEOUT: 'Модель не ответила за отведённое время.',
    PROCESS_FAILED: 'Сбой ИИ-runner при выполнении разбора.',
  } as Record<string, string>,
  failureHint: {
    INPUT_LIMIT: 'Сократите период или число транзакций и запустите анализ заново.',
    OUTPUT_LIMIT: 'Совет не сохранён. Запросите его ещё раз; если ошибка повторяется, сообщите администратору.',
    INVALID_ANALYSIS: 'Запустите анализ заново; если ошибка остаётся, сообщите администратору.',
    INVALID_OUTPUT: 'Совет не сохранён. Запросите его ещё раз.',
    UNKNOWN_EVIDENCE_REFERENCE: 'Совет не сохранён. Запросите его ещё раз.',
    TIMEOUT: 'Повторите запрос позже.',
    PROCESS_FAILED: 'Повторите запрос; если ошибка повторяется, сообщите администратору.',
  } as Record<string, string>,
  unavailable: {
    CREDENTIAL_NOT_CONFIGURED: 'Не настроен ключ доступа к модели.',
    DOCKER_UNAVAILABLE: 'Docker недоступен.',
    RUNTIME_IMAGE_MISSING: 'Нет закреплённого образа runtime.',
    OS_ISOLATION_NOT_PROVEN: 'Не подтверждена изоляция процесса.',
    RUNNER_ARTIFACT_MISSING: 'Не найдены файлы runtime или пакет Qwen Code.',
    RUNNER_ARTIFACT_MISMATCH: 'Пакет Qwen Code не совпадает с закреплённым.',
    MODEL_ENDPOINT_UNAVAILABLE: 'Сервис модели недоступен.',
    MODEL_CONFIG_INVALID: 'Файл конфигурации моделей не читается или не проходит проверку.',
  } as Record<string, string>,
  unavailableHint: {
    CREDENTIAL_NOT_CONFIGURED: 'Администратору: задайте LT_VERDICT_AI_CREDENTIAL_ENV_FILE (docs/user/advisory-ai.md).',
    DOCKER_UNAVAILABLE: 'Запустите Docker и повторите запрос.',
    RUNTIME_IMAGE_MISSING: 'Администратору: загрузите образ командой docker pull из docs/user/advisory-ai.md.',
    OS_ISOLATION_NOT_PROVEN: 'Администратору: изоляцию не удалось подтвердить на этом компьютере (раздел про изоляцию в docs/user/advisory-ai.md).',
    RUNNER_ARTIFACT_MISSING: 'Администратору: проверьте LT_VERDICT_AI_QWEN_ROOT и состав поставки (docs/user/advisory-ai.md).',
    RUNNER_ARTIFACT_MISMATCH: 'Администратору: установите Qwen Code 0.21.1 (docs/user/advisory-ai.md).',
    MODEL_ENDPOINT_UNAVAILABLE: 'Проверьте доступ сервера к сервису модели и повторите позже.',
    MODEL_CONFIG_INVALID: 'Администратору: исправьте файл LT_VERDICT_AI_MODELS_FILE и перезапустите LT Verdict; код ошибки записан в stderr процесса (docs/user/advisory-ai.md).',
  } as Record<string, string>,
}
