// Строки экрана «Поды сервиса» (платформа, P4c). Это диагностическая проекция: слов о причине здесь нет.
export const POD_LABELS = {
  title: 'Поды сервиса',
  note: 'Диагностическая проекция, не основание вердикта',
  lead: 'Значения подов по плечам из файла pod-view. Вердикт строится по рядам сервисов и от этих данных не зависит.',
  show: 'Показать данные по подам',
  hint: 'Загрузка читает файл pod-view на сервере (при каждом запросе заново); поэтому она запускается по кнопке.',
  loading: 'Ищу данные по подам…',
  armTitle: (arm: string | null) => arm === null ? 'Плечо не указано' : `Плечо ${arm}`,
  none: 'Нет данных по подам: ни в одном анализе с тем же плечом и тем же снимком ресурсов pod-view не подавался.',
  noneHow: 'Файл готовит tools/pod_view_adapter.py; его подают в повторный анализ того же входа (--pod-view или часть pod_view задания).',
  failed: (message: string) => `Данные по подам не получены: ${message}`,
  mismatch: 'Файл pod-view не соответствует плечу или снимку этого анализа; данные не показаны.',
  service: 'Сервис',
  metric: 'Метрика',
  view: 'Вид',
  map: 'Тепловая карта',
  table: 'Таблица подов',
  noMetric: 'У выбранного сервиса нет строк.',
  loadingRows: 'Загружаю строки сервиса…',
  coverage: (included: number, observed: number) => `В файле pod-view: ${included} из ${observed} подов.`,
  coverageReduced: 'Охват сокращён: файл содержит не все поды. Отсутствующие поды не показаны и в выводах не участвуют.',
  selection: (kind: string, metric?: string, limit?: number) => kind === 'ALL' ? 'Отбор подов при подготовке файла не применялся.' : `Отбор при подготовке файла: ${kind}${metric ? `, метрика ${metric}` : ''}${limit ? `, не более ${limit} подов` : ''}.`,
  shown: (shown: number, total: number) => `На карте ${shown} из ${total} строк метрики, худшие по максимуму сверху; остальные - в таблице.`,
  gridMismatch: 'Сетки времени плеч различаются: карты показаны раздельно и не сравниваются по колонкам.',
  unitMismatch: (units: string) => `Единицы метрики у плеч различаются (${units}): у каждой карты своя шкала цвета.`,
  scale: (min: string, max: string, unit: string) => `Шкала цвета: от ${min} до ${max} ${unit}. Штриховка - нет данных.`,
  mapLabel: (arm: string | null, service: string, metric: string, rows: number, columns: number) => `${POD_LABELS.armTitle(arm)}, ${service}, ${metric}: тепловая карта, ${rows} строк, ${columns} колонок`,
  readout: (label: string, time: string, value: string) => `${label}, ${time} UTC: ${value}`,
  readoutHint: 'Наведите указатель на клетку, чтобы увидеть значение; полный текстовый вид - в таблице подов.',
  missing: 'нет данных',
  heads: ['Под', 'Контейнер', 'Максимум', 'Среднее', 'Последнее'],
  tableRegion: (arm: string | null) => `Таблица подов, ${POD_LABELS.armTitle(arm)}`,
  more: (count: number) => `Показать ещё ${count}`,
  tableNote: 'Статистики считаются на клиенте по всем колонкам сетки; пропуски в них не участвуют. «Последнее» - последнее наблюдённое значение.',
}
