import { expect, test } from '@playwright/test'

test('history loads explicitly and exports only selected rows with loaded options', async ({ page }) => {
  let historyReads = 0
  page.on('request', request => { if (new URL(request.url()).pathname.endsWith('/analytics')) historyReads++ })
  await page.goto('/')
  await page.getByTestId('input-file').setInputFiles({ name: 'analytics-fixture.jtl', mimeType: 'text/csv', buffer: Buffer.from('timeStamp,elapsed,label,success\n1767225610000,125,analytics-test,true\n') })
  await page.getByRole('button', { name: 'Analyze run', exact: true }).click()
  await expect(page.locator('#verdict')).toContainText('NO_POLICY')
  const panel = page.locator('#saved-analytics-panel')
  await expect(panel).toBeVisible()
  expect(historyReads).toBe(0)
  await panel.getByRole('button', { name: 'Refresh analytics', exact: true }).click()
  const rows = panel.getByRole('region', { name: 'Run dynamics table' }).locator('tbody tr')
  await expect(rows.first()).toBeVisible()
  const originalCount = await rows.count()
  await panel.getByText('Select runs shown and exported', { exact: true }).click()
  await panel.getByRole('checkbox').first().uncheck()
  await expect(rows).toHaveCount(originalCount - 1)
  await panel.getByLabel('Comparable runs', { exact: true }).fill('50')
  const href = await panel.getByRole('link', { name: 'Export analytics JSON', exact: true }).getAttribute('href')
  expect(new URL(href!, page.url()).searchParams.get('limit')).toBe('10')
  const exported = await page.request.get(href!)
  expect(exported.status()).toBe(200)
  expect((await exported.json()).dynamics.rows).toHaveLength(originalCount - 1)
  const html = await panel.getByRole('link', { name: 'Export dynamics HTML', exact: true }).getAttribute('href')
  const report = await page.request.get(html!)
  expect(report.status()).toBe(200)
  expect(await report.text()).toContain('not recalculated after row selection')
})
